### ISSUE TITLE
Make BUniverse shortcode easier to use in combination with CMB2 Oembed

### ISSUE THREAD

**Issue by alana29s** [bu-ist/responsive-framework#126]
The BUniverse shortcode only accepts a video id. 
The wp_oembed_get is not returning results if using a BUniverse URL.

For a better user experience using the CMB2 OEMBED field type is preferred for adding a video on the backend.

Research why the wp_oembed_get function is not working properly with BUniverse URLs. Or update the BUniverse shortcode to accept a url so we can keep the regex in one place.

See the workaround for `r-thurman` using a regex in the child theme that needs simplification standardization. https://github.com/bu-ist/r-thurman/pull/12

**Comment by acketon** [comment]
Also consider the same for the Kaltura platform.

**Comment by hirozed** [comment]
@westsbu Where is this in the roadmap?  For Diversity, I'd like to say that they can use BUniverse and Kaltura links in their new resource library.  

I propose we create a plugin for this.  The functionality doesn't need to be tied to a theme, and would be useful across all sites.

If we can bump this up the queue, I can take it.

**Comment by hirozed** [comment]
@alana29s When I was working on the [Kaltura Oembed](https://github.com/bu-ist/responsive-framework/pull/287), I tested BUniverse.  It worked within the content area as well as within a CMB2 oembed field.  

I can give this another test if you think it's still broken.

**Comment by alana29s** [comment]
@hirozed The Thurman project is closed and working with updates referenced. I trust your judgement, if you know BUniverse to be working correctly, please feel free to close the issue.
