### ISSUE TITLE
Allow the default font palette to be filterable

### ISSUE THREAD

**Issue by ashleykolodziej** [bu-ist/responsive-framework#13]
_From @desrosj on April 2, 2018 19:54_

Currently, the default font palette option is hardcoded as `f1`. This is problematic for a few reasons.

- The font palette options will be filterable after #385. If default is removed as an allowed palette option, the disallowed option will be returned by `responsive_font_options()` and `responsive_get_font_palette()`.
- A companion or child theme that does not want to define the BU_RESPONSIVE_FONT_PALETTE constant, but wants to enforce a different default layout is unable to do so.
- If BU_RESPONSIVE_FONT_PALETTE is defined but is defined as a palette that was filtered out of the options, it will always be `f1`.

Allowing the default font palette to be filtered solves this.

Related #385.

_Copied from original issue: bu-ist/responsive-framework-1x#386_

**Comment by ashleykolodziej** [comment]
_From @desrosj on April 2, 2018 19:55_

Also related: #366.

**Comment by toddmilliken** [comment]
@ashleykolodziej I think we closed this out with PR https://github.com/bu-ist/responsive-framework/pull/134 , documented on this issue https://github.com/bu-ist/responsive-framework/issues/12 . Do you want to close this issue or do we need more work to be done? The filter now exists for modifying default fonts; nothing else was done regarding the constant for BU_RESPONSIVE_FONT_PALETTE
