### ISSUE TITLE
Add Filter to header.php to alter <header>

### ISSUE THREAD

**Issue by acketon** [bu-ist/responsive-framework#138]
### Expected behavior: Magic

In One Editorial I ran into a case where I needed to duplicate header.php because the <header> in the framework had to be replace/modified. If possible it would be nice to have a filter to alter or not output this markup: 

https://github.com/bu-ist/responsive-framework/blob/1f5a8ae7c49d0d3406acc53fc536c9ecefce07e4/header.php#L59-L64

**Comment by ashleykolodziej** [comment]
Hey @acketon! Can you tell me a little more about what you needed to alter/remove here? It might help to have a link to the file in One Editorial as well.

**Comment by acketon** [comment]
It looks like this was added in v3 here: https://github.com/bu-ist/responsive-framework-3x/blob/develop/header.php

can this be back ported to v2?

**Comment by acketon** [comment]
At this point I don't think it's worth adding to V2 now that we are starting to build almost all new themes in v3
