### ISSUE TITLE
Customizer UI, responsive_font_options, and font palette CSS don't agree on anything

### ISSUE THREAD

**Issue by ashleykolodziej** [bu-ist/responsive-framework#14]
_From @ashleykolodziej on August 25, 2017 17:56_

Right now, the Customizer UI, responsive_font_options, and font palette CSS are completely disconnected. This has led to an issue with the fourth font option, where the UI says one thing, the label says another, and the CSS is off doing its own thing.

![image](https://user-images.githubusercontent.com/1828613/29726092-80ae0be8-899c-11e7-8ef2-cd87ec250b74.png)

Meanwhile, the CSS says it should be Tiempos headline, Benton body copy: https://github.com/bu-ist/responsive-framework/blob/master/css/f4.css#L57-L70

Getting the UI text out of a static image is the first step in resolving this issue. In the best world, the CSS and this option would be able to talk to each other and generate the correct CSS, so that no disconnect can happen.

That said, we have that here with colors, and that's not exactly fun to maintain either: https://github.com/bu-ist/responsive-framework/issues/84

So in the short term, the UI should be reworked to drop the static image. In the long term, a cleaner solution for generating and maintaining CSS through Customizer is something we'll want to look at.

_Copied from original issue: bu-ist/responsive-framework-1x#238_

**Comment by stonybrookweb** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [https://github.com/bu-ist/responsive-framework/issues/14](https://trello.com/c/ayDN3lfW/38-https-githubcom-bu-ist-responsive-framework-issues-14)
