### ISSUE TITLE
Could use a hook before wp footer call

### ISSUE THREAD

**Issue by acketon** [bu-ist/responsive-framework#163]
https://github.com/bu-ist/responsive-framework/blob/333944f05e002402b00b4daebcbc8991486dc22a/footer.php#L65

**Comment by acketon** [comment]
found this issue was using the before closing body tag hook to add a div wrapping around the entire page. When logged in the admin bar is inside the new div I added and is then positioned relative to that div instead of the body of the page. (it was getting pushed down from the top of the browser window)

I fixed it by adding my own hook to the r-editorial copy of footer.php but when this hook is added we should adjust the r-editorial theme to switch it to the framework hook

**Comment by toddmilliken** [comment]
@acketon Why not use the `wp_footer` action hook instead? https://developer.wordpress.org/reference/hooks/wp_footer/

This would be complete if we add in the `wp_body_open` hook available in 5.2 https://make.wordpress.org/themes/2019/03/29/addition-of-new-wp_body_open-hook/ . This way you could add a page-wrapper in that way (everything in between the `<body />` tag.

**Comment by ashleykolodziej** [comment]
This appears to be solved.
