### ISSUE TITLE
Responsive Nav Hooks don't appear to work if BU navigation is enabled. 

### ISSUE THREAD

**Issue by acketon** [bu-ist/responsive-framework#166]
it appears that the before/after hooks to add markup in here:
https://github.com/bu-ist/responsive-framework/blob/49298f7366464c0bbfe25b9947014e8579197d38/inc/template-tags.php#L336

aren't replicated here: 
https://github.com/bu-ist/responsive-framework/blob/49298f7366464c0bbfe25b9947014e8579197d38/inc/bu-template-tags.php

They don't seem to be working for me... do they need to be added again?

**Comment by toddmilliken** [comment]
They should probably exist in both cases. Soon we will migrate that function override into https://github.com/bu-ist/bu-responsive-customizations .
