### ISSUE TITLE
get_the_exerpt( $post ) does not pull the excerpt if outside of the loop and the post does not have an excerpt

### ISSUE THREAD

**Issue by hirozed** [bu-ist/responsive-framework#168]
### Expected behavior:
The post excerpt should fall back to an excerpted version of the post content.  This is when the excerpt is within a function that is outside of the primary loop.

### Actual behavior:
Instead of grabbing from the post content of the post in question, it will take the excerpt from the primary loop's post.

### Possible Solution
@toddmilliken proposed a helper function within `r-cas-companion` that will take care of the issue.  I propose adding `strip_shortcodes()` to the helper.
https://github.com/bu-ist/r-cas-companion/blob/master/includes/template-tags.php#L38-L80

https://core.trac.wordpress.org/ticket/36934 if you would like some light reading.
https://core.trac.wordpress.org/changeset/44941 is the final code that got put into 5.2.0

**Comment by toddmilliken** [comment]
Lets add a helper function and ship! 🚀 

I keep adding the same helper to my child themes
