### ISSUE TITLE
bu-profiles-default-list.php doesn't seem to get loaded

### ISSUE THREAD

**Issue by acketon** [bu-ist/responsive-framework#219]
Working on the Profiles directory for SPH and it appears with a Page set to use the Profiles.php template from Responsi (not one in the theme) and set to "default" the template in responsi `https://github.com/bu-ist/responsive-framework/blob/develop/bu-profiles-default-list.php` never is loaded and used. Instead the profiles plugin uses the one in the plugin's codebase. 

This means we can't override that default listing template part? Seems to be a bug. The Advanced layout if selected loads the `profile-advanced.php` from Responsi.

**Comment by acketon** [comment]
ah, a bug in bu-profiles and  PR that was approved but never merged would fix this: https://github.com/bu-ist/bu-profiles/issues/6

**Comment by ashleykolodziej** [comment]
Closed in https://github.com/bu-ist/bu-profiles/issues/6
