### ISSUE TITLE
Constants

### ISSUE THREAD

**Issue by mustafauysal** [bu-ist/responsive-framework#223]
**List of existing constants:** https://github.com/bu-ist/responsive-framework/wiki/PHP-Constants

There are several constants prefixed with `BU_` -- those could be renamed, since they could still be useful in the parent theme, and could be overridden in the child.

**Comment by mustafauysal** [comment]
@ashleykolodziej Here is the list of contents and actions. We can rename some of those constants, but it would be better if we can rid off the BU specific constants.

| Constant                                             | Action                                  |
| ---------------------------------------------------- | --------------------------------------- |
| RESPONSIVE_FRAMEWORK_VERSION                         | Leave as it  |
| RESPONSIVE_CHILD_THEME_VERSION                       | Leave as it  |
| RESPONSIVE_MODERNIZR_VERSION                         | Leave as it  |
| RESPONSIVE_LIGHTGALLERY_VERSION                      | Leave as it  |
| RESPONSIVE_LG_THUMBNAIL_VERSION                      | Leave as it  |
| BU_RESPONSIVE_POSTS_SIDEBAR_SHOW_BOTTOM              | Rename `RESPONSIVE_POSTS_SIDEBAR_SHOW_BOTTOM`  |
| BU_RESPONSIVE_SIDEBAR_POSITION                       | Rename `RESPONSIVE_SIDEBAR_POSITION`  |
| BU_RESPONSIVE_LAYOUT                                 | Rename `RESPONSIVE_LAYOUT`  |
| BU_SUPPORTS_DYNAMIC_FOOTBARS                         | Removed  - filter is available `responsive_theme_supports_dynamic_footbars` |
| BU_RESPONSIVE_FONT_PALETTE                           | Rename `RESPONSIVE_FONT_PALETTE`  |
| BU_SUPPORTS_COMMENTS                                 | Remove constant and direct call `bu_supports_comments` -  we are maintaining the old logic with `responsive_has_comment_support` filter  |
| BU_SUPPORTS_SEO                                      | Remove from framework and define in custom plugin |
| BU_DISABLE_FOOTER_EDITOR                             | Remove from framework and define in custom plugin |
| BU_NAVIGATION_SUPPORTED_DEPTH                        | Remove from framework and define in custom plugin |
| BU_BRANDING_TYPE                                     | It doesn't seem in use, don't do anything |
| BU_PROFILES_PLUGIN_ACTIVE                            | Remove: we likely move profiles.php to plugin |
| BU_SITE_MANAGER_VERSION                              | Remove from framework - it will be used for migration script in custom plugin |

**Comment by ashleykolodziej** [comment]
`BU_BRANDING_TYPE` is really for child themes - it restricts the customizer options so that you can't change which branding type is in use. We can definitely remove. :)

`BU_SUPPORTS_COMMENTS` has been funky for a while - I'm in favor of removing that as well. It might help with this long outstanding issue: https://github.com/bu-ist/responsive-framework/issues/141

**Comment by mustafauysal** [comment]
`BU_PROFILES_PLUGIN_ACTIVE` will be removed when we remove the profile template. #35
