### ISSUE TITLE
BU Calendar

### ISSUE THREAD

**Issue by mustafauysal** [bu-ist/responsive-framework#227]
**Related plugin:** https://github.com/bu-ist/bu-calendar-plugin

**Templates**
- [ ] `calendar.php` https://github.com/bu-ist/responsive-framework/blob/develop/page-templates/calendar.php
- [ ] `template-parts/calendar` https://github.com/bu-ist/responsive-framework/tree/develop/template-parts/calendar

**Functionality**
- [ ] `inc/calendar.php` https://github.com/bu-ist/responsive-framework/blob/develop/inc/calendar.php

**Comment by mustafauysal** [comment]
Here is my plan for removing the functionalities and templates like this;

* Register a template directory in the custom plugin. This way we can register custom page templates. (It can be calendar, profile or any other bu specific templates)
* Move functionalities to the custom plugin.

@ashleykolodziej What do you think about this? Also, any thoughts about cleaning up the stylings? (e.g https://github.com/bu-ist/responsive-framework-3x/blob/develop/css/default.css#L115-L123)

**Comment by ashleykolodziej** [comment]
I like this idea!

For cleaning up styles - those are managed in Responsive Foundation. https://github.com/bu-ist/responsive-foundation/tree/develop/css-dev/burf-theme/calendar If you want to take a crack at that, go for it - but it's written in Sass, so you'll need to create a new branch and recompile the Sass in the framework using that branch.
