### ISSUE TITLE
BU Branding

### ISSUE THREAD

**Issue by mustafauysal** [bu-ist/responsive-framework#229]
**Related plugin:** https://github.com/bu-ist/bu-branding

**Functionality**
- [ ] `inc/branding.php` https://github.com/bu-ist/responsive-framework/blob/develop/inc/branding.php
- [ ] `responsive_branding_copyright` https://github.com/bu-ist/responsive-framework/blob/develop/functions.php#L729-L738

**Comment by mustafauysal** [comment]
`responsive_branding_copyright` has already moved into the plugin.

I think we need to remove template partials too. 
* `template-parts/footer-branding.php`
* `template-parts/branding.php`  - `responsive_branding()` renders the output with that partial. 

@ashleykolodziej Do we want to remove branding markups entirely? I'm thinking about adding new hooks to manage branding related outputs from the outside of the framework.

**Comment by ashleykolodziej** [comment]
Yeah, we shouldn't have BU branding on the open source version of the framework, so removing it is the best option.
