### ISSUE TITLE
BU Post Lists

### ISSUE THREAD

**Issue by mustafauysal** [bu-ist/responsive-framework#232]
**Related plugin:** https://github.com/bu-ist/bu-post-lists

**Templates**
- [x] `page-templates/news.php` https://github.com/bu-ist/responsive-framework/blob/develop/page-templates/news.php
- [x] `template-parts/news.php` https://github.com/bu-ist/responsive-framework/blob/develop/template-parts/news.php

**Functionality**
- [x] `inc/post-lists.php` https://github.com/bu-ist/responsive-framework/blob/develop/inc/post-lists.php

**Comment by mustafauysal** [comment]
@thrijith  As a next step, I think we should follow a similar approach as calendar templates.

1) Register news template - https://github.com/bu-ist/bu-responsive-customizations/blob/develop/inc/class-template-loader.php#L50-L52
2) Move template parts to custom plugin
3) Move functionalities by considering the custom plugin's convention (namespace, hook initialization etc..)

@ashleykolodziej thoughts?

**Comment by ashleykolodziej** [comment]
This makes complete sense to me. Go for it! 💯
