### ISSUE TITLE
BU Profiles - Functionality

### ISSUE THREAD

**Issue by mustafauysal** [bu-ist/responsive-framework#235]
**Related plugin:** https://github.com/bu-ist/bu-profiles

**Functionality**
- [ ] `inc/profiles.php` https://github.com/bu-ist/responsive-framework/blob/develop/inc/profiles.php
- [x] `register_sidebar` https://github.com/bu-ist/responsive-framework/blob/develop/functions.php#L250-L262
- [x] `responsive_profiles_archive_link` https://github.com/bu-ist/responsive-framework/blob/develop/inc/template-tags.php#L811-L838

**Comment by mustafauysal** [comment]
I think we can just move https://github.com/bu-ist/responsive-framework/blob/develop/inc/profiles.php to the custom plugin. 

>  register_sidebar https://github.com/bu-ist/responsive-framework/blob/develop/functions.php#L250-L262

Already addressed in:  https://github.com/bu-ist/bu-responsive-customizations/commit/d11a5a515b3b781e7666c30a5e190e22f81d09d7#diff-06792f4a052c5ca16a127838cd2690d6R245-R257

>  responsive_profiles_archive_link https://github.com/bu-ist/responsive-framework/blob/develop/inc/template-tags.php#L811-L838

Already addressed in: https://github.com/bu-ist/bu-responsive-customizations/commit/5072cfb434937ec7af5cfcc5c6986744f813acd9

@ashleykolodziej

**Comment by ashleykolodziej** [comment]
🙌 this plan looks great!
