### ISSUE TITLE
BU Profiles - Templates

### ISSUE THREAD

**Issue by mustafauysal** [bu-ist/responsive-framework#236]
**See**  https://github.com/bu-ist/responsive-framework/issues/35

- [ ] https://github.com/bu-ist/responsive-framework/blob/develop/bu-profiles-advanced.php
- [ ] https://github.com/bu-ist/responsive-framework/blob/develop/bu-profiles-basic.php
- [ ] https://github.com/bu-ist/responsive-framework/blob/develop/bu-profiles-default-list.php
- [ ] https://github.com/bu-ist/responsive-framework/blob/develop/bu-profiles-mini.php
- [ ] https://github.com/bu-ist/responsive-framework/blob/develop/archive-profile.php
- [ ] https://github.com/bu-ist/responsive-framework/blob/develop/single-profile.php
- [ ] https://github.com/bu-ist/responsive-framework/blob/develop/profiles.php
- [ ] https://github.com/bu-ist/responsive-framework/blob/develop/template-parts/profile-advanced.php
- [ ] https://github.com/bu-ist/responsive-framework/blob/develop/template-parts/profile-basic.php
- [ ] https://github.com/bu-ist/responsive-framework/blob/develop/template-parts/profile-mini.php

**Comment by mustafauysal** [comment]
> https://github.com/bu-ist/responsive-framework/blob/develop/bu-profiles-advanced.php
> https://github.com/bu-ist/responsive-framework/blob/develop/bu-profiles-basic.php
> https://github.com/bu-ist/responsive-framework/blob/develop/bu-profiles-default-list.php
> https://github.com/bu-ist/responsive-framework/blob/develop/bu-profiles-mini.php

and related partials

> https://github.com/bu-ist/responsive-framework/blob/develop/template-parts/profile-advanced.php
> https://github.com/bu-ist/responsive-framework/blob/develop/template-parts/profile-basic.php
> https://github.com/bu-ist/responsive-framework/blob/develop/template-parts/profile-mini.php

seems to be used in https://github.com/bu-ist/bu-profiles/blob/develop/bu-profiles.php#L348
I think that creating a wrapper function of `locate_template` that seeks the templates files in the plugin's template directory first would work here. This way, template files can be overridden by the child theme when it necessary, and it can use the templates that shipped with the plugin by default.

> https://github.com/bu-ist/responsive-framework/blob/develop/archive-profile.php
> https://github.com/bu-ist/responsive-framework/blob/develop/single-profile.php
> https://github.com/bu-ist/responsive-framework/blob/develop/profiles.php

move templates to custom plugin and alter default lookup with the `get_query_template` hook (eg: `single_template` for `single-profile.php`)

@thrijith @ashleykolodziej thoughts?

**Comment by ashleykolodziej** [comment]
This is where my knowledge on specifics gets a bit fuzzy, but at a high level this 100% makes sense to me. I'm going to rely on @thrijith to be the expert on the specifics here, but I think this is a great plan based on my understanding and what we talked about.
