### ISSUE TITLE
Footbar Functionality

### ISSUE THREAD

**Issue by mustafauysal** [bu-ist/responsive-framework#237]
* footbar functionality
	* Issue: The attributes start are prefixed with "bu_"
	* Proposal: Rename the attributes or move all of the functionality to the child theme or plugin.

**Comment by mustafauysal** [comment]
@ashleykolodziej Is this about dynamic footbars? If so, it might be useful to keep in the framework.

(If the attributes/settings are renamed, the old settings will need to be renamed too during the framework upgrade.)

**Comment by ashleykolodziej** [comment]
Yeah, this should stay.

**Comment by thrijith** [comment]
Hi @ashleykolodziej,

Can you please confirm if no action is required for this issue? 
Thanks

**Comment by ashleykolodziej** [comment]
I see what this was asking. The functionality should stay, but attributes should be renamed and migrated in the upgrade script.
