### ISSUE TITLE
Audit the framework for any remaining BU-specific functionality and identify where it goes here

### ISSUE THREAD

**Issue by thrijith** [bu-ist/responsive-framework#239]
- Do a detailed check on the code to make sure no code is left behind that doesn't belong in the framework.

- Check locally along with un-merged, bu-profiles and bu-access-controls-bumc-additions changes and make sure everything is in place.

cc: @ashleykolodziej

**Comment by thrijith** [comment]
Verify usage of functionality in framework.

- Footbar metabox registration, should stay as option to enable / disable is done in customizer - [here](https://github.com/bu-ist/responsive-framework-3x/blob/622e2cfecd714efc29c21092f5890dfacc8998ca/admin/admin.php#L21-L39)

- namespaces updates [for](https://github.com/bu-ist/responsive-framework-3x/blob/develop/admin/responsive-admin-page-template-filter.php#L8)

- Functions / attributes / options with `burf_` prefixes

- `bu_responsive_primary_nav_args` maybe rename this [filter](https://github.com/bu-ist/responsive-framework-3x/blob/develop/inc/bu-template-tags.php#L40), found no usage of it. 

- Move [buniverse_shortcode](https://github.com/bu-ist/responsive-framework-3x/blob/develop/inc/buniverse.php) to plugin.

- `remove_action( 'admin_menu', array( 'BuInterfaceModifications', 'hide_customizer' ) );`, the function is not available in mu-plugin, hence it can be removed, [ref](https://github.com/bu-ist/responsive-framework-3x/blob/develop/inc/customizer.php#L8-L19).

- [filter](https://github.com/bu-ist/responsive-framework-3x/blob/develop/inc/search-form.php) in `inc/search-form.php`, can be moved to custom plugin.

cc: @ashleykolodziej

**Comment by ashleykolodziej** [comment]
@thrijith This looks fantastic! Thank you for finding these last few missing pieces. Can you work on them? I think they all make sense.
