### ISSUE TITLE
Prevent users from switching back to Flexi

### ISSUE THREAD

**Issue by ashleykolodziej** [bu-ist/responsive-framework#241]
Flexi is a deprecated framework. In all versions of Responsive, we would like to prevent switching back to Flexi once you have migrated off of it.

**Comment by thrijith** [comment]
@ashleykolodziej I don't see an option to disable the activation button of the listed themes, but I think one of the following options can be used instead:

- We can use `wp_prepare_themes_for_js`, to filter the theme list on page and remove flexi from the page all together.
- We can use `allowed_themes` to filter the theme list on network and remove flexi framework, the theme will still be listed on themes page but user will get an error when trying to activate it.

We can add the filter in a mu-plugin and conditionally check if current active theme is responsive and unset flexi framework using anyone of the above options, please share your thoughts.

Thanks!

**Comment by ashleykolodziej** [comment]
@thrijith This sounds like a good plan to me. Can we go with the second option? I think I can add something to the descriptions of the Flexi framework and related themes to make it clear you can't go back from Responsive to those, but I think they should still be visible so people don't ask why they aren't there.

Can you open a pull request to https://github.com/bu-ist/bu-core for these changes (this is an MU plugin that we use for this kind of thing) and make sure the following themes are disabled if the current theme or parent framework is one of the following?

**Responsive 1x**
bu-new-media-default
bu-new-media-gray
bu-new-media-black
bu-new-media-red
flexi-framework
flexi-red
flexi-banner-blue
flexi-staffer
flexi-kenmore
flexi-green
flexi-medical
flexi-commave
flexi-official
flexi-dark
flexi-toplevel

**Responsive 2x**
All of the above, plus Responsive 1x

**Responsive 3x**
All of the above, plus Responsive 2x

Alternately - can we filter the `allowed_themes` list by parent framework? So, for example, anyone trying to move to _any_ flexi child theme or the flexi framework from Responsive gets an error?

**Comment by thrijith** [comment]
@ashleykolodziej I've opened a [PR](https://github.com/bu-ist/bu-core/pull/23) at `bu-core`, based on the above info, here is a [video](https://drive.google.com/file/d/1NNMJ8WX4q8I-NPFK1Ey87wggzYiKcN4l/view?usp=sharing) that displays the change, please let me know if that is what you expected, Thanks!

**Comment by ashleykolodziej** [comment]
Site admins shouldn't be able to switch themes. This is unrelated to the Framework.
