### ISSUE TITLE
Output registration as a link on single calendar pages

### ISSUE THREAD

**Issue by ashleykolodziej** [bu-ist/responsive-framework#255]
### Responsive Version:
2x

### Expected behavior:
The registration link field on a single calendar page should output as a link, not plain text.

### Actual behavior:
It outputs as plain text.

### Link(s) where this can be reproduced:
https://www-staging.bu.edu/met/events/?eid=244195

**Comment by stonybrookweb** [comment]
The `registration_url` field is a custom field added to the Met Calendar, not a standard field.
It is best handled via the `responsive_calendar_get_fields_custom` filter to modify.
See bu-ist/r-met#47
