### ISSUE TITLE
Gutenberg Callout

### ISSUE THREAD

**Issue by ashleykolodziej** [bu-ist/responsive-framework#26]
_From @ashleykolodziej on September 19, 2016 21:4_

Something we should consider adding. Here's an ongoing list of examples of how people are doing it on their own within the framework:

http://www.bu.edu/cgsnow/
http://www.bu.edu/cftcc/ (Custom CSS)
http://www.bu.edu/asian/
http://www.bu.edu/artsadmin/
http://www.bu.edu/arion/
http://www.bu.edu/darstaff/
http://www.bu.edu/econ/
http://www.bu.edu/fluidlab/research/
http://www.bu.edu/globalhealthtechnologies/ (Custom CSS)
http://www.bu.edu/rotc/
http://www.bu.edu/sourcing/ (Custom CSS)
http://www.bu.edu/sswit/

_Copied from original issue: bu-ist/responsive-framework-1x#90_

**Comment by ashleykolodziej** [comment]
_From @sr4136 on December 5, 2016 19:36_

Do we need this if we have a Layout Builder (#40) ?

**Comment by ashleykolodziej** [comment]
@sr4136 Depends on how we do the layout builder. If we tailor what kinds of stuff people are able to put in, no. If it's something more like Mesh or SED's landing page layout, where it's like you choose the number of columns and get a bunch of TinyMCE editors - yes.

**Comment by ashleykolodziej** [comment]
This should be built using Gutenberg.

**Comment by acketon** [comment]
Duplicate of: https://github.com/bu-ist/bu-blocks/issues/277

**Comment by ashleykolodziej** [comment]
Closing as duplicate of https://github.com/bu-ist/bu-blocks/issues/277
