### ISSUE TITLE
Hide Profiles.php Unless BU Profiles Plugin is Activated

### ISSUE THREAD

**Issue by acketon** [bu-ist/responsive-framework#266]
Profiles.php page template shows up in the dropdown of page templates even when the BU Profiles plugin is disabled. It doesn't make sense to show it if the plugin is not enabled. Related to #35.

**Comment by aremery** [comment]
It's easy enough to unregister the template if the plugin is not activated. Here's a[ pull request](https://github.com/bu-ist/responsive-framework/pull/277). We can merge it and be done with it but is this really how we want to handle this? Why is the infrastructure designed in a way that the template for the plugin is not in the plugin? Is there a good reason? Should we be propagating this design pattern?

**Comment by aremery** [comment]
@acketon do you want the above pr merged?
