### ISSUE TITLE
Do not hide event titles on calendar pages when using BU Banners, even if a custom title is added to the calendar template page

### ISSUE THREAD

**Issue by ashleykolodziej** [bu-ist/responsive-framework#270]
### Responsive Version: 
2x with BU Banners installed

### Expected behavior:
On single event calendar pages, both the banner AND the event title should always show, even if you add a custom title to the banner.

### Actual behavior:
On single event calendar pages, the banner shows, but the event title is hidden using the visually hidden class.

### Link generated by [whatsmybrowser.org](https://www.whatsmybrowser.org/):
Affects all browsers.

### Link(s) where this can be reproduced:
- https://www.bu.edu/tsai/visit/calendar/ (Banner title is added to this page)
- https://www.bu.edu/tsai/visit/calendar/?eid=254891 (Demonstration of missing event title)

### Steps to reproduce:
1. Activate BU Banners on a site.
2. Ensure BU Calendar is enabled.
3. Add a banner, including a custom title, to the calendar template page (main calendar page).
4. Visit a single event. It will use the main calendar's banner title, and hide the event title.

### Screenshot (if this is a bug):
<img width="2591" alt="Screen Shot 2021-07-19 at 12 03 28 PM" src="https://user-images.githubusercontent.com/1828613/126191194-0d1199d5-a0d4-4a29-91c2-9d17d6fe4bb5.png">

### Related ServiceNow Ticket number (if available):
INC13261584

### Related code:
I believe the code that controls this is over here: https://github.com/bu-ist/responsive-framework/blob/b8d401fd7007ddbc57c09299d40f205c475ab1c2/inc/bu-banners.php#L118-L142

**Comment by aremery** [comment]
@ashleykolodziej 
There's a list of conditions that need to be true for the class to be applied. I feel the safest way is to add to that check, not to be a calendar event. so:  if bla and bla and bla **AND not a calendar single**  give me the hidden class. That way we know it won't effect anything else

Here's a pull request!!! 
https://github.com/bu-ist/responsive-framework/pull/273

**Comment by smtierneybu** [comment]
@aremery if this is closed, please update the tags to remove on dev list and needs resourcing so that we know it is all set.
