### ISSUE TITLE
IMAP: alignment of profiles in wordpress advanced format?

### ISSUE THREAD

**Issue by SigurdTheBruce** [bu-ist/responsive-framework#309]
### Description from Client

We're using the profiles plugin within wordpress to display people associated with our event (as instructed here: https://www.bu.edu/tech/services/cccs/websites/www/wordpress/how-to/profiles/)  and I've noticed that depending upon the length of an individual's title, their photos, and the lines beneath each profile, don't always correctly align in a grid as desired when using [bu_list_profiles format="advanced" ].

Please see: https://www.bu.edu/imap/events/fall-2023-workshop/  as an example.  It looks ok in the first set with our Advisory Board, but then the grid becomes misaligned in the faulty section below. Is this something that you can fix within the advanced format code?   Or do you have any advice as to how we can address this on our end beyond trying to edit everyone's titles to be the same length (not feasible)?

### Link to ServiceNow Ticket

https://bu.service-now.com/incident.do?sysparm_tiny=269938c1973ee5909a3a7be0f053af05&sys_id=0bd69e4797d7a9509a3a7be0f053af3e&sysparm_record_row=9

**Comment by acacase** [comment]
Fixed with Custom CSS as this is a Custom CSS site.
