### ISSUE TITLE
Make calendar labels filterable

### ISSUE THREAD

**Issue by ashleykolodziej** [bu-ist/responsive-framework#33]
I just got a request on Dining to change the "Registration" text here to "Learn More". I don't think it makes sense to override the entire calendar page template over this, especially as we'll likely be revisiting this template very soon to clean it up. What are the possibilities for making labeling for this template flexible at the child theme level?

Relevant code here:

https://github.com/bu-ist/responsive-framework/blob/master/page-templates/calendar.php#L294

**Comment by toddmilliken** [comment]
At the very least, a filter could be added for that one occurrence.

How many other words are hardcoded in this template/theme? I'm wondering if maybe we should have a function that you can pass a value into to return a hardcoded word from an array of hardcoded words. 

For example, this could exist in the parent theme somewhere:

```
if ( ! function_exists( 'responsive_get_hardcoded_word' ) ) {
	/**
	 * Retrieve a hardcoded word from the theme.
	 *
	 * @param string $key The array key to pluck from the words array.
	 * @return string $word.
	 */
	function responsive_get_hardcoded_word( $key = '' ) {

		$words = array(
			'more_text'         => __( 'Learn More', 'responsive-framework' ),
			'registration_text' => __( 'Register Now', 'responsive-framework' ),
		);

		$words = apply_filters( 'responsive_filter_hardcoded_words', $words );

		if ( ! empty( $words[ $key ] ) ) {
			return $words[ $key ];
		}
	}
}
```

And a child theme could then add a filter to change those hardcoded words only:
```
/**
 * Child theme: Filter parent-theme's hardcoded responsive words.
 *
 * Changes registration text.
 *
 * @param array $words An array of hardcoded words in responsive theme.
 * @return array $words
 */
function my_child_theme_words( $words ) {
	$words['registration_text'] = __( 'Learn More', 'child-theme-textdomain' );
	return $words;
}
add_filter( 'responsive_filter_hardcoded_words', 'my_child_theme_words' );
```

Or the child theme could overwrite the entire function if they want to change a bunch of things at once.

That's just one possible approach but it may not be the best solution!

**Comment by ashleykolodziej** [comment]
@toddmilliken I took a peek through all of Responsive and it's really Calendar and Profiles that are the main places we'd want the ability to change text, I think. These strike me as places that might have similar issues later:

https://github.com/bu-ist/responsive-framework/blob/master/profiles.php#L16
https://github.com/bu-ist/responsive-framework/blob/master/archive-profile.php#L13

Everything else is mostly admin text or so standard I can't forsee a need to change it that wouldn't end up likely requiring something bigger (like a new custom post type) or bigger edits to the page that would require the whole thing to be overridden. Since profiles and calendar come from different plugins, I think we should consider keeping things to adjust them separate too, in case we want to move those pieces into the plugins down the line. So the basic idea here makes sense to me - I just think we should keep separate filters for Calendar and Profiles, if that makes sense.

**Comment by toddmilliken** [comment]
Yup -- then perhaps a simple filter will do the trick on https://github.com/bu-ist/responsive-framework/blob/master/page-templates/calendar.php#L294

Could change:
```
<dt class="single-event-registration-label">Registration:</dt>
```
to be updated to:
```
<dt class="single-event-registration-label">
	<?php echo esc_html( apply_filters( 'responsive_calendar_registration_text', 'Registration:' ) ); ?>
</dt>
```
or maybe add the i18n function for translating:
```
<dt class="single-event-registration-label">
	<?php
	echo esc_html( apply_filters( 'responsive_calendar_registration_text', function() {
		return __( 'Registration:', 'responsive-framework' );
	} ) );
	?>
</dt>
```

Child themes would modify doing:
```
/**
 * Override the parent theme's calendar registration text.
 *
 * @param string $registration_text Defaults to "Register Now:" in parent-theme.
 * @return string $registration_text
 */
function child_theme_registration_text( $registration_text ) {
	// Overrides the default "Registration:" text.
	$registration_text = __( 'Learn More', 'textdomain' );
	return $registration_text;
}
add_filter( 'responsive_calendar_registration_text', 'child_theme_registration_text' );
```

**Comment by ashleykolodziej** [comment]
Makes sense to me! I was taking a glance through the rest of the labels to see if there was any reason to filter them all, but I think filtering them all gets us going down a slippery slope where the labels in the BU Calendar backend UI no longer match what's happening on the page. That's not ideal, so I think you've got the right idea restricting it to just this field. Looks good to me 💃

**Comment by toddmilliken** [comment]
I've made some headway refactoring the template on the [feature/calendar-template-refactor](feature/calendar-template-refactor) branch. Separating out all the logic at the top of the template into functions, removing need for global variables, and breaking down the template into template-partials that can be overwritten. 

I'm going to do some testing tomorrow on the dining and bands sites in my sandbox to see if the refactor broke anything.

If all is well, I'll also add in a filter for you to change all those labels at the child theme which would give you further flexibility for modifying this content.
