### ISSUE TITLE
Add BU Banners Default Templates

### ISSUE THREAD

**Issue by stonybrookweb** [bu-ist/responsive-framework#38]
Add default Banner templates to responsive-framework.

As we move along in the development of the BU-Banners plugin in usage with responsive-framework we have found the need to couple some functionality between the two, especially in the case of Banner Titles and Page Titles as evidenced by #36 & https://github.com/bu-ist/responsive-framework-1x/pull/423 in the prior repo with the addition of `r_page_title_class `.

Usage of these filters and functions has occurred in the code of BU-Banners plugin making it potentially more difficult to outsource the BU-Banners plugin in the future.

The goal is to restore the BU-Banners default functionality, and allow the custom functionality that we need in responsive-framework. The precedent that we have for this already is how the course feed overrides work. https://github.com/bu-ist/responsive-framework/blob/master/inc/course-feeds.php

The one downfall to this is that we will have to keep the templates in responsive-framework in sync as much as possible with the default templates in BU-Banners. The custom child themes should not be an issue because they will usually have their own custom templates created.

This is also another good reason to work towards open sourcing both repos, so we can recommend to use BU-Banners with responsive-framework as it will include more functionality.

@ashleykolodziej, @hirozed, @toddmilliken 
This is a summary of our conversations, please add anything I missed.

**Comment by toddmilliken** [comment]
>The goal is to restore the BU-Banners default functionality, and allow the custom functionality that we need in responsive-framework. 

I agree 100%. We can remove some of these ties in `bu-banners`, and instead use `responsive-framework` to hook into `bu-banners` to change plugin functionality. 

It sounds like there are 2 things you mentioned we need to resolve to break the ties:

1. The page titles. To get around this, lets add filters and hooks to `bu-banners` where it outputs the title that will allow themes to customize this (for example, defaulting to the page title if empty). We can make the html heading tags + the title text filterable in the plugin so `responsive-framework` can modify what kind of tag banners uses, and jam in a page title if meta field is left empty. Im thinking this would look a lot like what we're proposing to do with the new `responsive_the_title` function and its filters https://github.com/bu-ist/responsive-framework/blob/feature/feature/bu-banners-has-page-title/inc/template-tags.php#L59 . We can definitely make progress on this issue and close it out quickly.

2. Banner templates exist in `responsive-framework`.  I haven't done a deep-dive into templating with `bu-banners`, but many plugins include default templates that may be overwritten in themes. Woocommerce for example provides template partials in its plugin, but before including them checks if there are overrides at the parent theme or child theme level. If no theme overrides exist, it will default to its plugin templates. Is there an issue with going with this approach? Without knowing much about the two repos, are there any problems with including basic templates at the plugin level? And is there even a need to overwrite them in `responsive-framework`? I would think that would be a child-theme issue that we would ideally like to reduce the occurrence of. This issue may require much more discussion, maybe a meeting would help.

**Comment by toddmilliken** [comment]
All banner functionality will begin to be migrated to https://github.com/bu-ist/bu-responsive-customizations . This is where we can add the title functionality, modified CMB2 title field  description, activate the plugin on bu-site-init, upgrade routines, etc.

Regarding the BU Banners templates -- I agree that we shouldn't need to include any. The plugin has a default template that covers the layouts it offers out-of-the-box. We'd only need to include them if Framework needed to modify the templates for whatever reason. Since there doesn't seem to be a reason to do so, we can probably close this issue.

**Comment by ashleykolodziej** [comment]
We've solved this problem by creating BU Responsive Customizations, and future banner templates can go there. Now that we have a strategy, we can close this, and return to it once there's more specific functionality we need for banner templates. Moving this to bu-banners for historical context.
