### ISSUE TITLE
Add custom fields support to Calendar template

### ISSUE THREAD

**Issue by ashleykolodziej** [bu-ist/responsive-framework#39]
@Adam42 notes that there are new `has_custom_fields` and `get_custom_fields` functions available in the calendar, which is a good first step towards not hard-coding custom fields in templates. Let's add it to the calendar template!

**Comment by Adam42** [comment]
Example of using these functions is in the README for calendar plugin: https://github.com/bu-ist/bu-calendar-plugin#example-of-retrieving-a-single-event-and-programatically-displaying-its-custom-fields

**Comment by Adam42** [comment]
Just realized that `html_type` isn't documented anywhere but is an essential property for when going about displaying custom fields dynamically without any hard-coding of the fields:

https://github.com/bu-ist/bu-calendar-plugin/blob/292c01caab9f443c6ba347a21de40486ffbcb941/README.md#html-type--attribute

For now these values are added manually to the database so let me know if there's any fields that should have an `html_type`. I think we can assume a default that if a custom_field has no `html_type` it's just a straight line(s) of text and can be rendered dynamically by just wrapping it in a `<p>`.

**Comment by toddmilliken** [comment]
This is ready for review in Framework and Foundation:
https://github.com/bu-ist/responsive-framework/pull/161
https://github.com/bu-ist/responsive-foundation/pull/213

**Comment by toddmilliken** [comment]
This feature has been merged in last release https://github.com/bu-ist/responsive-framework/releases/tag/2.3.3 in this PR https://github.com/bu-ist/responsive-framework/pull/161
