### ISSUE TITLE
Unnecessary menu button on small screens when no menu items

### ISSUE THREAD

**Issue by amckenz** [bu-ist/responsive-framework#49]
_From @anton-kachurin on July 19, 2018 14:30_

### Responsive Version:
2.1.0

### Expected behavior:
No menu button on small screens when site doesn't have menu elements

### Actual behavior:
There's a menu button on small screens when site doesn't have menu elements

### Link(s) where this can be reproduced:
https://www.bu.edu/404

### Steps to reproduce:

1. Use small browser window size
2. Go to https://www.bu.edu/404
3. Click on the hamburger icon and see how the nav bar enlarges a notch.

### Screenshot (if this is a bug):
![image](https://user-images.githubusercontent.com/23388231/42948986-ba74c976-8b3e-11e8-8de3-2d9f65604c9a.png)

_Copied from original issue: bu-ist/responsive-framework-1x#426_

**Comment by ashleykolodziej** [comment]
Yeah, there's really no way to check for this - it's on the user to decide the appropriate layout for them. Closing.
