### ISSUE TITLE
Action hooks inside content area

### ISSUE THREAD

**Issue by amckenz** [bu-ist/responsive-framework#59]
_From @ashleykolodziej on May 29, 2018 18:2_

### Responsive Version: 2.0

https://github.com/bu-ist/responsive-framework/blob/develop/template-parts/content.php

Right now, we do not have action hooks inside the `<article>` tag. I vaguely remember saying this probably wasn't necessary. Boy was I wrong. Let's add it in.

_Copied from original issue: bu-ist/responsive-framework-1x#406_

**Comment by amckenz** [comment]
_From @stonybrookweb on May 30, 2018 13:19_

There are several things to consider before adding this.

Should we move the article to a template part so we only need one set of hooks? Or do we add the hooks on both the default page.php and the no-sidebars.php.

Where this situation occurred on r-hub, we had already copy pasted the page.php to a custom page template just to register CMB2 boxes. So we could have used custom hooks in this case, because the page template was already copied, adding to the framework wouldn't have helped in the moment. 

Or since this was already a custom template we could have just included the CMB2 created section anywhere on that custom template, but that would not be in the spirit of the action hooks and responsi-2-x. But since this CMB2 created section was only being used once maybe including it on the custom page template is best?

Do the_content and the_title filters give us the tools we already need?

Do the comments and sharing tools need better action hooks?

And most importantly, to keep in the spirit of using the hooks how do we register CMB2 boxes to appear only on designated "page templates" in the back end for data entry without creating duplicates of page.php and no-sidebars.php. If we don't solve this problem, any updates to these action hooks will not be updated in existing custom themes without manually updating all the copies of those templates.

**Comment by amckenz** [comment]
_From @ashleykolodziej on June 4, 2018 14:43_

Possibly related to https://github.com/bu-ist/responsive-framework/issues/226

**Comment by toddmilliken** [comment]
Agreed. We should be able to hook in before/after post content, and then before/after structural tags like section and article so we can append content easily. This should be a quick win to add in 👍

**Comment by ashleykolodziej** [comment]
Todd already did this
