### ISSUE TITLE
Alternate footbar widget count class is incorrect

### ISSUE THREAD

**Issue by ashleykolodziej** [bu-ist/responsive-framework#6]
### Expected behavior:

Alternate footbar should output the widget count of the alternate footbar, not the regular footbar.

### Actual behavior:

The widget count for alternate footbar is the same as regular footbar. For example, if regular has 9 widgets, and alternate has 2, the class will be `widget-count-9` on alternate.

### Steps to reproduce:

1. Go to Customizer > Content Options > Enable Alternate Footbar
2. Edit a page and set it to use the alternate footbar
3. Add widgets to the alternate footbar and regular footbar - make sure there is a different number of widgets in each.
4. Check page output on both a footbar and alternate footbar page, and note that classes/widget count are the same.

### Screenshot (if this is a bug):

![screen shot 2018-07-11 at 9 54 49 am](https://user-images.githubusercontent.com/1828613/42577616-b3f904a6-84f2-11e8-8ec2-921cc332d6e9.png)

**Comment by stonybrookweb** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Alternate footbar widget count class is incorrect](https://trello.com/c/HKFTzUpr/37-alternate-footbar-widget-count-class-is-incorrect)
