### ISSUE TITLE
Share color / typography customizations across a group of sites

### ISSUE THREAD

**Issue by amckenz** [bu-ist/responsive-framework#60]
_From @ashleykolodziej on May 25, 2018 15:56_

### Responsive Version: 2.x

One interesting thing I'm noticing is that there are sites who definitely all share the same color/typography settings, to create a kind of consistent experience across related sites. Here's an example:

http://www.bumc.bu.edu/clinepi/
http://www.bumc.bu.edu/cmu/
http://www.bumc.bu.edu/compbiomed/
http://www.bumc.bu.edu/cra/

There's probably at least 10 or 15 more of these. Which brings up an interesting question - does it make sense to centrally manage these settings across a group of sites?

_Copied from original issue: bu-ist/responsive-framework-1x#405_

**Comment by amckenz** [comment]
_From @ashleykolodziej on May 25, 2018 16:7_

This is also coming up with Custom CSS:

http://www.bumc.bu.edu/ohra/
http://www.bumc.bu.edu/irb/
http://www.bumc.bu.edu/crro/

**Comment by ashleykolodziej** [comment]
This is no longer relevant with companion themes.
