### ISSUE TITLE
Version 2.0 Documentation

### ISSUE THREAD

**Issue by amckenz** [bu-ist/responsive-framework#73]
_From @desrosj on March 1, 2018 18:32_

A running list of things that need to be documented.

**Functions/code examples**

- [x] Filter: Loading a custom build of Modernizr (`r_enqueue_modernizr`)
- [x] Filter: Adding news templates (`responsive_news_templates`)
- [x] Filter: Adding `responsive-scripts` script dependencies (`r_script_dependencies`)
- [x] Filter: Making the blog page wide instead of narrow(`r_narrow_blog_page`)
- [x] Filter: Specifying narrow single templates (`r_narrow_single_templates`)
- [x] Filter: Specifying narrow archive templates (`r_narrow_archive_templates`)
- [x] Filter: Adding classes to the content container (`r_content_container_class`)
- [x] Action hooks: How to use theme action hooks to insert  markup.
- [x] Fancy Galleries: How to output a fancy gallery with code (from a CMB2 box), and properly enqueueing the scripts (#274).

**Written Explanations**

- [x] Action hooks
- [x] Filter hooks
- [x] Narrow Templates
- [x] Header templates being renamed to "Mastheads".
- [x] Using template action hooks to avoid having to override template files.
- [x] Fancy Galleries
- [x] Proper page template structures (starter theme?)
- [x] Proper template parts (starter theme?)
- [x] Overriding sidebar templates.
- [x] Sections
- [x] #282 
- [x] CSS class names that have changed
- [x] `r_get_template_part()`
- [x] Upgrading or modifying the Modernizr version.
- [x] Upgrading or modifying the Lightgallery script.

**1x Documentation Pages to Review**

- [x] Configure Grunt for Fun and Profit
- [x] Customize Javascript
- [x] Documentation-Template
- [x] Flexi-Migrations
- [x] Framework-Development-and-Release-Workflows
- [x] Functions-Guidelines.md DELETED OR RENAMED
- [x] Getting-Started
- [x] ~Git-Workflow~
- [x] Grunt-Configuration
- [x] Home
- [x] Hotfixes DELETED in favor of [Framework Development and Release Workflows](https://github.com/bu-ist/responsive-framework/wiki/Framework-Development-and-Release-Workflows)
- [x] ~Javascript Plugins and APIs~
- [x] Launch-your-theme
- [x] ~Master SASS Variables List~
- [x] Merging and Creating a Pull Request
- [x] PHP-Constants
- [x] PHP-Functions
- [x] PHP-Snippets
- [x] Pulling in Foundation Updates
- [x] ~Questions~
- [x] README DELETED OR MOVED
- [x] ~Reference~
- [x] Responsive Video Shortcode
- [x] ~SASS-Documentation~
- [x] SASS-Grid
- [x] Sass-best-practices
- [x] Setting up Github Repositories
- [x] Shortcodes
- [x] Starting a New Project
- [x] Starting a new Child Theme
- [x] Temp PHP Code Patterns
- [x] Temp-GitFlow MOVED OR DELETED
- [x] Testing Your changes
- [x] ~URL & Templates to style~

_Copied from original issue: bu-ist/responsive-framework-1x#334_

**Comment by ashleykolodziej** [comment]
Huge props to @hirozed for finishing up the last of these! I've verified everything is all done.
