### ISSUE TITLE
How do we clarify editing/compiling JS?

### ISSUE THREAD

**Issue by amckenz** [bu-ist/responsive-framework#74]
_From @ashleykolodziej on February 28, 2018 16:52_

Right now, you can edit JS in two places depending on what you need - a single file to compile to `scripts.js` sitewide (which means you work in `js-dev`) or work directly in the `js` folder to create separate files. This can be confusing for new designers and developers. What's the best way to clarify this? Do we need a workflow change? Documentation?

History of this question here: https://github.com/bu-ist/responsive-framework/pull/299

_Copied from original issue: bu-ist/responsive-framework-1x#326_

**Comment by toddmilliken** [comment]
This does sound confusing. I believe we should all be editing in js-dev just like we do with css-dev.

I think we just need to account for ability to have more root files compile (not just everything going to scripts.js). We can accomplish this by levelling up our JS workflow in general. It would look a little something like this:

- Add babel via a grunt task or wrapper that can convert es6+ back into es5
- Define entry point files in js-dev. These entry points could be like `theme.js` and `admin.js`. Each entry point will contain a series of imports just like sass file. The imports are the smaller files dedicated to each JS task. For example: `admin.js` could be an entry point and we could `@import 'metaboxes';` to add admin metabox JS functionality. `theme.js` could contain all things that should get compiled to a theme js file, such as `@import 'mobile-menu';` or `@import 'fancybox'`.

Then the `js/` folder would just be those compiled entry point files. You would be able to add as many entry points as you'd want so this could be flexible.

I've assigned myself this task. Once we have it nailed down, we'll also want to copy this workflow to child theme starter, and start utilizing it in plugins.

The goal is to leverage es6 functionality for easier maintainability and to be less reliant on modifying grunt files for concatenating files together, and establish a common pattern to maintain JS in our projects.
