### ISSUE TITLE
What functionality should be moved to plugins?

### ISSUE THREAD

**Issue by ashleykolodziej** [bu-ist/responsive-framework#8]
_From @ashleykolodziej on November 29, 2016 16:40_

Some functionality in Responsive should really be at the plugin level. What should we move, and what is the most appropriate plugin to move it to? Ongoing list of proposed places to move stuff below.

### BU Branding

[`responsive_is_bu_domain()`](https://github.com/bu-ist/responsive-framework/blob/develop/inc/template-tags.php#L33-L37)

_Copied from original issue: bu-ist/responsive-framework-1x#114_

**Comment by ashleykolodziej** [comment]
During this scrub, let's look for anything that might prevent us from going open source, including BU dependencies.

**Comment by hirozed** [comment]
Below is my review.  I might have missed some, but this is the bulk of items that could be either moved to a child theme or plugin.

# Functionality to remove from Responsi 

## Move to a child theme or centralized plugin
* `bu-profiles-advanced/basic/default-list/mini.php`
* `archive-profile.php`
* `no-access-bumc.php`
* `no-access.php`
* `single-profile.php`
* `archive-profile.php`
* `profiles.php`
* `bu-profiles-advanced.php`
* `bu-profiles-basic.php`
* `bu-profiles-default-list.php`
* `bu-profiles-default-mini.php`
* `sidebar-profiles.php`
* `bu-site-init.php` -- the child theme can handle the init instead of the parent
* `inc/`
	* `activation.php`
	* `branding.php`
	* `course-feeds.php`
	* `calendar.php`
	* `bu-banners.php`
	* `migration-helpers.php`
	* `post-lists.php`
	* `serch-form.php`
	* `sharing.php`
	* `upgrade.php` (Is this even still needed?)
* `page-templates`
	* `news.php`
* `template-parts`
	* `news.php`
	* `profile-advanced.php`
	* `profile-basic.php`
	* `profile-mini.php`
	* `profile.php`

## Sections to refactor
* `responsive_search_form` & supporting functions
	* Issue: Refers to the BU specific search
	* Proposal: Change to a hook that can use the BU search as an override in the child theme.
* footbar functionality
	* Issue: The attributes start are prefixed with "bu_"
	* Proposal: Rename the attributes or move all of the functionality to the child theme or plugin.
* `functions.php`
	* `responsive_setup_nav_menus`
		* Lines 160-163: The check for BU Navigation can be moved to a child functions.php
	* `responsive_setup_misc_filters` - move to child
	* `responsive_setup_news_templates` - move to child
	* `responsive_sidebars`
		* Lines 250-262: Move the sidebar creation for Profiles to the child theme
	* `responsive_change_title_tag` - move to child
		* Line 697: Move the `remove_filter` to child
	* `r_remove_news_template` - move to child
	* `responsive_branding_copyright` - move to child
	* Any `require`s at the end of the file that are BU related, with their associated files.  If they can be moved into a central plugin (they aren't theme-functionality), they should go there.  Everything else goes into the child theme.
* `header.php`
	* Replace lines 22-32 with a hook and move the lines into a function taking advantage of the hook 
* `inc/customizer.php`
	* Lines 913, 921, 922 -- related to `bu-collapsible` class.  Move to child theme sass?
* `inc/template-tags.php`
	* `responsive_get_the_title`
	* Line 152: This elseif needs refactoring to remove the `bu_profile` call from the logic.  However, that logic should be move to a child theme in a way that it doesn't break functionality of this function.
	* `responsive_is_bu_domain` - move to child
	* `responsive_has_comment_support` - move to child
	* `responsive_comments` - move to child if it is only needed in tandem with the above comment function
	* `responsive_search_form` - move to child
	* `responsive_primary_nav` - refactor to move the `bu_navigation` functionality to child, leaving a hook in place to override.
	* `responsive_post_meta`
	* Line 641 - Refactor to a hook, allowing `bu_supports_comments` to override the default in a child theme
	* `responsive_get_posts_archive_link`
	* Line 710: Move the news pages functionality to child, calling either a new hook or the existing filter
	* `responsive_profiles_archive_link` - move to child
	* `responsive_get_footbar_id` - move to child

## Other notes
* There are several constants prefixed with `BU_` -- those could be renamed, since they could still be useful in the parent theme, and could be overridden in the child.
* The tests need to be reviewed and updated, moved to child, or removed.

**Comment by ashleykolodziej** [comment]
This is fantastic! A few notes:

- `upgrade.php` is still needed - that's for converting Flexi sites to Responsive. Definitely keep that around. I believe it also handles 1x to 2x conversion. We still have tons of these sites out there.
- If the footbar functionality refers to the alternate footbar option, I think that'd be nice to just rename instead of removing from the open source version. 
- `inc/customizer.php` - We're removing custom color palettes soon due to MWAS (see https://github.com/bu-ist/responsive-framework/issues/22), so this will be a non-issue soon! 🎉 

And one ✨ special note ✨ about BU Navigation - that plugin is actually open source. So, technically, if you really wanted to, you could leave it in and we'd be okay to open source. But I think that's a decision we should talk through and make as a group. 

This looks really fantastic!

**Comment by hirozed** [comment]
The footbar functionality is mostly within `admin.php` lines 21-81.  I think just renaming or removing the `bu_` prefix in front of the meta will satisfy the deBUness.

**Comment by ashleykolodziej** [comment]
Just ran across this issue that may be related to or impact how we structure this. https://github.com/bu-ist/responsive-framework/issues/60

**Comment by ashleykolodziej** [comment]
We did this!!!
