### ISSUE TITLE
Separate GitHub templates for bugs vs. ideas

### ISSUE THREAD

**Issue by amckenz** [bu-ist/responsive-framework#81]
_From @ashleykolodziej on January 25, 2018 22:43_

Github just released multiple issue template support - let's use it! https://github.com/blog/2495-multiple-issue-and-pull-request-templates #

_Copied from original issue: bu-ist/responsive-framework-1x#295_

**Comment by ashleykolodziej** [comment]
Closed in https://github.com/bu-ist/responsive-framework/commit/8ba5f4079e378650574d20482d727a2316a2a444
